### PR TITLE
Rails 4.2 support

### PR DESCRIPTION
**Pull request by k0nserv**
This PR is based on the work by @nulian in https://github.com/nulian/activerecord_enum.

The tests pass for ActiveRecord 4.2, but I am not very familiar with the Rails type system so I might have made some mistakes

I've also updated rspec to 3.1 and changed to use the expect syntax

### CODE REVIEW

**Comment by iangreenleaf** [comment]
Fantastic, thanks for getting this in a better state for merging. I went ahead and cherry-picked the rspec update commit into master already since that one is stable and doesn't affect the rest of the PR. Travis has unfortunately decided to start failing builds of this project, but it's nothing to do with that commit, it's all passing for me locally.

The new rake task looks nice, but it's failing for me with the same unhelpful error that is showing up on Travis. It would be great if you can figure out what's going on with that.

I'll take a closer look at the 4.2 changes in a few days, hopefully.

**Comment by k0nserv** [comment]
Great :) I will look at the 1.9.3 issue and see if I can figure out why it's failing.

**Comment by k0nserv** [comment]
There we go

**Comment by iangreenleaf** [comment]
Awesome, thanks so much. Pulled those commits in too, so now the 4.2 stuff is the only change left that I need to look at.

**Comment by nulian** [comment]
Nice making it ready for the gem. Didn't have much time lately for this but at least you could use my changes to get it ready for the gem.

**Comment by toshi-kawanishi** [comment]
:+1:

**Comment by fruwe** [comment]
:+1:

**Comment by k0nserv** [comment]
We have been using this for our app since I submitted this PR and it works well

**Comment by fruwe** [comment]
Same here

**Comment by zvibo** [comment]
Hi Zvi here from Kiva.  This is a desperately needed enhancement for us!  Thank you!  Will definitely be interested in any issues you can find in k0nserv's PR!

**Comment by iangreenleaf** [comment]
Hey! Sorry for letting this go for so long. I have not in fact forgotten about it, I just got busy and it kept slipping down my to-do list. But, tonight or tomorrow I should hopefully be able to get to it.

**Comment by zvibo** [comment]
Thanks for the quick response, iangreenleaf!  Look forward to the updates tonight or tomorrow (and your take on them).  Thanks so much for your help!

**Comment by iangreenleaf** [comment]
Thank you all for your work on this! This is now merged and released as 0.4.0.

**Comment by fruwe** [comment]
Thanks a lot

**Pull request merged**
